# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 06:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_profile_detail_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rname', models.CharField(max_length=200)),
                ('rtype', models.CharField(max_length=100)),
                ('rvalue', models.CharField(max_length=100)),
                ('runit', models.CharField(max_length=100)),
                ('ravail', models.CharField(max_length=50)),
                ('cloud_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Profile')),
            ],
        ),
    ]
