# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 06:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_resource'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='cloud_id',
            new_name='cloud',
        ),
    ]
