# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 07:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20170411_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='rpub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
            preserve_default=False,
        ),
    ]
