# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 06:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20170414_1143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question',
            new_name='id',
        ),
    ]
